from django.core.management.base import BaseCommand
from django.core.files import File
from core.models import Movie
from datetime import date
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
MEDIA_IMAGES = os.path.join(BASE_DIR, 'media', 'movie_images')
MEDIA_VIDEOS = os.path.join(BASE_DIR, 'media', 'movie_videos')

MOVIES = [
    {
        'title': 'Stranger Things',
        'description': 'When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces in order to get him back.',
        'release_date': date(2016, 7, 15),
        'genre': 'science_fiction',
        'length': 51,
        'image_card': 'card1.png',
        'image_cover': 'poster1.png',
        'video': 'movie_clip.mp4',
        'age_rating': 'TV-14',
        'is_featured': True,
    },
    {
        'title': 'Money Heist',
        'description': 'An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.',
        'release_date': date(2017, 5, 2),
        'genre': 'action',
        'length': 70,
        'image_card': 'card2.jpg',
        'image_cover': 'poster2.jpg',
        'video': 'movie_clip_BrNpigZ.mp4',
        'age_rating': 'TV-MA',
        'is_featured': False,
    },
    {
        'title': 'The Witcher',
        'description': 'Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.',
        'release_date': date(2019, 12, 20),
        'genre': 'fantasy',
        'length': 60,
        'image_card': 'card3.jpg',
        'image_cover': 'poster4.png',
        'video': 'movie_clip_DwK6pEi.mp4',
        'age_rating': 'TV-MA',
        'is_featured': False,
    },
    {
        'title': 'Dark',
        'description': 'A missing child sets four families on a frantic hunt for answers as they unearth a mind-bending mystery that spans three generations.',
        'release_date': date(2017, 12, 1),
        'genre': 'mystery',
        'length': 55,
        'image_card': 'card4.jpg',
        'image_cover': 'card4.jpg',
        'video': 'movie_clip_INcks3p.mp4',
        'age_rating': 'TV-MA',
        'is_featured': False,
    },
    {
        'title': 'Squid Game',
        'description': 'Hundreds of cash-strapped players accept a strange invitation to compete in children\'s games. Inside, a tempting prize awaits with deadly high stakes.',
        'release_date': date(2021, 9, 17),
        'genre': 'thriller',
        'length': 55,
        'image_card': 'card5.jpg',
        'image_cover': 'poster5.webp',
        'video': 'movie_clip_okHtjGf.mp4',
        'age_rating': 'TV-MA',
        'is_featured': True,
    },
    {
        'title': 'The Crown',
        'description': 'Follows the political rivalries and romance of Queen Elizabeth II\'s reign and the events that shaped the second half of the twentieth century.',
        'release_date': date(2016, 11, 4),
        'genre': 'drama',
        'length': 58,
        'image_card': 'card6.jpg',
        'image_cover': 'card6.jpg',
        'video': 'movie_clip_tLArTRg.mp4',
        'age_rating': 'TV-MA',
        'is_featured': False,
    },
    {
        'title': 'Black Mirror',
        'description': 'An anthology series exploring a twisted, high-tech multiverse where humanity\'s greatest innovations and darkest instincts collide.',
        'release_date': date(2011, 12, 4),
        'genre': 'science_fiction',
        'length': 60,
        'image_card': 'card7.jpg',
        'image_cover': 'poster6.webp',
        'video': 'movie_clip_U9INJAC.mp4',
        'age_rating': 'TV-MA',
        'is_featured': False,
    },
    {
        'title': 'Narcos',
        'description': 'A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar, as well as the many other drug cartels that plagued the country through the years.',
        'release_date': date(2015, 8, 28),
        'genre': 'crime',
        'length': 49,
        'image_card': 'card9.jpg',
        'image_cover': 'poster9.webp',
        'video': 'movie_clip_uWUW5IL.mp4',
        'age_rating': 'TV-MA',
        'is_featured': False,
    },
    {
        'title': 'JoJo\'s Bizarre Adventure',
        'description': 'The story of the Joestar family, who are possessed with intense psychic strength, and the adventures each member encounters throughout their lives.',
        'release_date': date(2012, 10, 5),
        'genre': 'fantasy',
        'length': 24,
        'image_card': 'card1.png',
        'image_cover': 'poster7.jpg',
        'video': 'stardust-crusader-dio-jojo.3840x2160.mp4',
        'age_rating': 'TV-14',
        'is_featured': False,
    },
    {
        'title': 'Breaking Bad',
        'description': 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future.',
        'release_date': date(2008, 1, 20),
        'genre': 'crime',
        'length': 49,
        'image_card': 'card2.jpg',
        'image_cover': 'poster2.jpg',
        'video': 'movie_clip_BrNpigZ.mp4',
        'age_rating': 'TV-MA',
        'is_featured': False,
    },
    {
        'title': 'The Office',
        'description': 'A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.',
        'release_date': date(2005, 3, 24),
        'genre': 'comedy',
        'length': 22,
        'image_card': 'card3.jpg',
        'image_cover': 'poster4.png',
        'video': 'movie_clip_DwK6pEi.mp4',
        'age_rating': 'TV-14',
        'is_featured': False,
    },
    {
        'title': 'Spider-Man: Into the Spider-Verse',
        'description': 'Teen Miles Morales becomes the Spider-Man of his universe and must join with five spider-powered individuals from other dimensions to stop a threat to all reality.',
        'release_date': date(2018, 12, 14),
        'genre': 'animation',
        'length': 117,
        'image_card': 'card5.jpg',
        'image_cover': 'poster5.webp',
        'video': 'movie_clip_okHtjGf.mp4',
        'age_rating': 'PG',
        'is_featured': False,
    },
    {
        'title': 'The Shawshank Redemption',
        'description': 'Over the course of several years, two convicts form a friendship, seeking consolation and eventual redemption through basic compassion.',
        'release_date': date(1994, 9, 23),
        'genre': 'drama',
        'length': 142,
        'image_card': 'card6.jpg',
        'image_cover': 'card6.jpg',
        'video': 'movie_clip_tLArTRg.mp4',
        'age_rating': 'R',
        'is_featured': False,
    },
    {
        'title': 'The Social Dilemma',
        'description': 'Explores the dangerous human impact of social networking, with tech experts sounding the alarm on their own creations.',
        'release_date': date(2020, 1, 26),
        'genre': 'documentary',
        'length': 94,
        'image_card': 'card7.jpg',
        'image_cover': 'poster6.webp',
        'video': 'movie_clip_U9INJAC.mp4',
        'age_rating': 'PG-13',
        'is_featured': False,
    },
    {
        'title': 'The Conjuring',
        'description': 'Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.',
        'release_date': date(2013, 7, 19),
        'genre': 'horror',
        'length': 112,
        'image_card': 'card9.jpg',
        'image_cover': 'poster9.webp',
        'video': 'movie_clip_uWUW5IL.mp4',
        'age_rating': 'R',
        'is_featured': False,
    },
    {
        'title': 'Forrest Gump',
        'description': 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.',
        'release_date': date(1994, 7, 6),
        'genre': 'drama',
        'length': 142,
        'image_card': 'card1.png',
        'image_cover': 'poster1.png',
        'video': 'movie_clip.mp4',
        'age_rating': 'PG-13',
        'is_featured': False,
    },
    {
        'title': 'The Good Place',
        'description': 'A woman struggles to become a better person after she mistakenly finds herself in a utopian afterlife that rewards good behavior.',
        'release_date': date(2016, 9, 19),
        'genre': 'comedy',
        'length': 22,
        'image_card': 'card2.jpg',
        'image_cover': 'poster2.jpg',
        'video': 'movie_clip_BrNpigZ.mp4',
        'age_rating': 'TV-14',
        'is_featured': False,
    },
    {
        'title': 'Indiana Jones: Raiders of the Lost Ark',
        'description': 'In 1936, archaeologist and adventurer Indiana Jones is hired by the U.S. government to find the Ark of the Covenant before the Nazis can.',
        'release_date': date(1981, 6, 12),
        'genre': 'adventure',
        'length': 115,
        'image_card': 'card3.jpg',
        'image_cover': 'poster4.png',
        'video': 'movie_clip_DwK6pEi.mp4',
        'age_rating': 'PG',
        'is_featured': False,
    },
    {
        'title': 'Parasite',
        'description': 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
        'release_date': date(2019, 5, 30),
        'genre': 'thriller',
        'length': 132,
        'image_card': 'card4.jpg',
        'image_cover': 'card4.jpg',
        'video': 'movie_clip_INcks3p.mp4',
        'age_rating': 'R',
        'is_featured': False,
    },
    {
        'title': 'Planet Earth II',
        'description': 'David Attenborough returns with a breathtaking exploration of nature\'s most extraordinary habitats and the incredible animals that call them home.',
        'release_date': date(2016, 11, 6),
        'genre': 'documentary',
        'length': 60,
        'image_card': 'card5.jpg',
        'image_cover': 'poster5.webp',
        'video': 'movie_clip_okHtjGf.mp4',
        'age_rating': 'G',
        'is_featured': False,
    },
    {
        'title': 'Toy Story',
        'description': 'A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy\'s room.',
        'release_date': date(1995, 11, 22),
        'genre': 'animation',
        'length': 81,
        'image_card': 'card6.jpg',
        'image_cover': 'card6.jpg',
        'video': 'movie_clip_tLArTRg.mp4',
        'age_rating': 'G',
        'is_featured': False,
    },
    {
        'title': 'Gone Girl',
        'description': 'With his wife\'s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it\'s suspected that he may not be innocent.',
        'release_date': date(2014, 10, 3),
        'genre': 'mystery',
        'length': 149,
        'image_card': 'card7.jpg',
        'image_cover': 'poster6.webp',
        'video': 'movie_clip_U9INJAC.mp4',
        'age_rating': 'R',
        'is_featured': False,
    },
    {
        'title': 'Django Unchained',
        'description': 'With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation owner in Mississippi.',
        'release_date': date(2012, 12, 25),
        'genre': 'western',
        'length': 165,
        'image_card': 'card9.jpg',
        'image_cover': 'poster9.webp',
        'video': 'movie_clip_uWUW5IL.mp4',
        'age_rating': 'R',
        'is_featured': False,
    },
    {
        'title': '10 Things I Hate About You',
        'description': 'A pretty, popular teenager can\'t go out on a date until her ill-tempered older sister does.',
        'release_date': date(1999, 3, 31),
        'genre': 'romance',
        'length': 97,
        'image_card': 'card1.png',
        'image_cover': 'poster1.png',
        'video': 'movie_clip.mp4',
        'age_rating': 'PG-13',
        'is_featured': False,
    },
    {
        'title': 'Sherlock',
        'description': 'A modern update finds the famous sleuth and his doctor partner solving crime in 21st century London.',
        'release_date': date(2010, 7, 25),
        'genre': 'mystery',
        'length': 90,
        'image_card': 'card2.jpg',
        'image_cover': 'poster2.jpg',
        'video': 'movie_clip_BrNpigZ.mp4',
        'age_rating': 'TV-14',
        'is_featured': False,
    },
    {
        'title': 'Mad Max: Fury Road',
        'description': 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.',
        'release_date': date(2015, 5, 15),
        'genre': 'action',
        'length': 120,
        'image_card': 'card3.jpg',
        'image_cover': 'poster4.png',
        'video': 'movie_clip_DwK6pEi.mp4',
        'age_rating': 'R',
        'is_featured': True,
    },
    {
        'title': 'The Grand Budapest Hotel',
        'description': 'A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel\'s glorious years under an exceptional concierge.',
        'release_date': date(2014, 3, 28),
        'genre': 'comedy',
        'length': 99,
        'image_card': 'card4.jpg',
        'image_cover': 'card4.jpg',
        'video': 'movie_clip_INcks3p.mp4',
        'age_rating': 'R',
        'is_featured': False,
    },
    {
        'title': 'The Pianist',
        'description': 'A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.',
        'release_date': date(2002, 9, 25),
        'genre': 'drama',
        'length': 150,
        'image_card': 'card5.jpg',
        'image_cover': 'poster5.webp',
        'video': 'movie_clip_okHtjGf.mp4',
        'age_rating': 'R',
        'is_featured': False,
    },
    {
        'title': 'Coraline',
        'description': 'An adventurous 11-year-old girl finds another world that is a strangely idealized version of her frustrating home, but it has sinister secrets.',
        'release_date': date(2009, 2, 6),
        'genre': 'animation',
        'length': 100,
        'image_card': 'card6.jpg',
        'image_cover': 'card6.jpg',
        'video': 'movie_clip_tLArTRg.mp4',
        'age_rating': 'PG',
        'is_featured': False,
    },
    {
        'title': 'The Haunting of Hill House',
        'description': 'Flashing between past and present, a fractured family confronts haunting memories of their old home and the terrifying events that drove them from it.',
        'release_date': date(2018, 10, 12),
        'genre': 'horror',
        'length': 60,
        'image_card': 'card7.jpg',
        'image_cover': 'poster6.webp',
        'video': 'movie_clip_U9INJAC.mp4',
        'age_rating': 'TV-MA',
        'is_featured': False,
    },
    {
        'title': 'The Notebook',
        'description': 'A poor yet passionate young man falls in love with a rich young woman, giving her a sense of freedom, but they are soon separated because of their social differences.',
        'release_date': date(2004, 6, 25),
        'genre': 'romance',
        'length': 123,
        'image_card': 'card9.jpg',
        'image_cover': 'poster9.webp',
        'video': 'movie_clip_uWUW5IL.mp4',
        'age_rating': 'PG-13',
        'is_featured': False,
    },
]


class Command(BaseCommand):
    help = 'Seed the database with sample movies'

    def handle(self, *args, **options):
        if Movie.objects.count() > 0:
            self.stdout.write(f'Skipping: {Movie.objects.count()} movies already exist')
            return

        created = 0
        for data in MOVIES:
            movie = Movie(
                title=data['title'],
                description=data['description'],
                release_date=data['release_date'],
                genre=data['genre'],
                length=data['length'],
                age_rating=data.get('age_rating', 'TV-MA'),
                is_featured=data.get('is_featured', False),
            )

            img_card_path = os.path.join(MEDIA_IMAGES, data['image_card'])
            img_cover_path = os.path.join(MEDIA_IMAGES, data['image_cover'])
            video_path = os.path.join(MEDIA_VIDEOS, data['video'])

            if os.path.exists(img_card_path):
                with open(img_card_path, 'rb') as f:
                    movie.image_card.save(data['image_card'], File(f), save=False)
            if os.path.exists(img_cover_path):
                with open(img_cover_path, 'rb') as f:
                    movie.image_cover.save(data['image_cover'], File(f), save=False)
            if os.path.exists(video_path):
                with open(video_path, 'rb') as f:
                    movie.video.save(data['video'], File(f), save=False)

            movie.save()
            created += 1
            self.stdout.write(f'  + {movie.title}')

        self.stdout.write(self.style.SUCCESS(f'Seeded {created} movies'))
