# Generated by Django 6.0.7 on 2026-07-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_movielist'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age_rating',
            field=models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17'), ('TV-MA', 'TV-MA'), ('TV-14', 'TV-14'), ('TV-PG', 'TV-PG')], default='TV-MA', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('romance', 'Romance'), ('science_fiction', 'Science Fiction'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('animation', 'Animation'), ('documentary', 'Documentary'), ('mystery', 'Mystery'), ('crime', 'Crime'), ('adventure', 'Adventure'), ('western', 'Western')], max_length=100),
        ),
    ]
